services:
  db:
    image: postgres:16
    container_name: beka_potentialist-db
    environment:
      POSTGRES_DB: beka_potentialist
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d beka_potentialist"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./beka_potentialist
      dockerfile: docker/backend/Dockerfile
    container_name: beka_potentialist
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/beka_potentialist
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./beka_potentialist-frontend
      dockerfile: ../docker/frontend/Dockerfile
    container_name: beka_potentialist-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
