name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: beka_potentialist
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/beka_potentialist
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        working-directory: ./beka_potentialist
        run: chmod +x gradlew

      - name: Build backend with Gradle
        working-directory: ./beka_potentialist
        run: ./gradlew clean bootJar

      - name: Build and test frontend
        working-directory: ./beka_potentialist-frontend
        run: |
          npm install
          npm run build
          npm test -- --watchAll=false

      - name: Build Docker images
        run: docker-compose build

      - name: Run backend tests
        working-directory: ./beka_potentialist
        run: ./gradlew test

      # Optional: Push Docker images to registry
      # - name: Log in to DockerHub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Push images
      #   run: |
      #     docker tag beka_potentialist-backend ${{ secrets.DOCKERHUB_USERNAME }}/beka_potentialist-backend:latest
      #     docker push ${{ secrets.DOCKERHUB_USERNAME }}/beka_potentialist-backend:latest
      #     docker tag beka_potentialist-frontend ${{ secrets.DOCKERHUB_USERNAME }}/beka_potentialist-frontend:latest
      #     docker push ${{ secrets.DOCKERHUB_USERNAME }}/beka_potentialist-frontend:latest
